apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.13.2
        profile:
            VendorType: partner
            version: v1.2
        reportDigest: uint64:11476311455734451931
        chart-uri: https://github.com/komish/openshift-helm-charts/blob/main/tests/data/hc-e2e-vault-0.17.0.tgz?raw=true
        digests:
            chart: sha256:387569953f54e6af080547b9c298af8725e85fb31801ab5baffc18140a03d6a9
            package: d822d74c7eada5bf4fc0824425ec05ef9a8e67e1de4c92bdac982b612ae7dd74
        lastCertifiedTimestamp: "2024-01-18T15:58:59.329639-06:00"
        testedOpenShiftVersion: "4.12"
        supportedOpenShiftVersions: '>=4.2'
        webCatalogOnly: false
    chart:
        name: hc-e2e-vault
        home: https://www.vaultproject.io
        sources:
            - https://github.com/hashicorp/vault
            - https://github.com/hashicorp/vault-helm
            - https://github.com/hashicorp/vault-k8s
            - https://github.com/hashicorp/vault-csi-provider
        version: 0.17.0
        description: Official HashiCorp Vault Chart
        keywords:
            - vault
            - security
            - encryption
            - secrets
            - management
            - automation
            - infrastructure
        maintainers: []
        icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.8.4
        deprecated: false
        annotations:
            charts.openshift.io/name: vault
        kubeversion: '>= 1.14.0-0'
        dependencies: []
        type: ""
    chart-overrides: ""
results:
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : registry.connect.redhat.com/hashicorp/vault-k8s:0.14.0-ubi
        Image is Red Hat certified : registry.connect.redhat.com/hashicorp/vault:1.8.4-ubi
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist

